### ISSUE TITLE
Undefined method for `description` for custom resource systemd_service from cookbook systemd

### ISSUE THREAD

**Issue by kmott** [nathwill/chef-nomad#29]
Hi,

I am playing around with getting a Nomad cookbook wrapper setup, and I am getting the error message below.  This is a freshly 'chef generate' cookbook, with no changes, except to load dependencies & the nomad::default recipe to see how it works.

```
       [ ... snip ... ]
       resolving cookbooks for run list: ["nomad_wrapper::default"]
       Synchronizing Cookbooks:
         - nomad_wrapper (0.1.0)
         - nomad (0.12.1)
         - ark (3.1.0)
         - seven_zip (2.0.2)
         - windows (3.1.1)
         - systemd (3.0.2)
         - build-essential (8.0.3)
         - compat_resource (12.19.0)
         - ohai (5.1.0)
         - mingw (2.0.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/nomad_wrapper/recipes/default.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `description' for Custom resource systemd_service from cookbook systemd
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/systemd/libraries/mixin.rb:36:in `block in build_dsl'
         /tmp/kitchen/cache/cookbooks/nomad/recipes/manage.rb:22:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/nomad/recipes/manage.rb:21:in `from_file'
         /tmp/kitchen/cache/cookbooks/nomad/recipes/default.rb:20:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/nomad/recipes/default.rb:19:in `each'
         /tmp/kitchen/cache/cookbooks/nomad/recipes/default.rb:19:in `from_file'
         /tmp/kitchen/cache/cookbooks/nomad_wrapper/recipes/default.rb:6:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/systemd/libraries/mixin.rb:
       
        29:  
        30:        module ClassMethods
        31:          def build_dsl
        32:            define_method(:method_missing) do |name, *args, &blk|
        33:              if @context && respond_to?("#{@context}_#{name}".to_sym)
        34:                send("#{@context}_#{name}".to_sym, *args, &blk)
        35:              else
        36>>               super(name, *args, &blk)
        37:              end
        38:            end
        39:  
        40:            define_method(:respond_to_missing?) do |name, include_private|
        41:              if @context && respond_to?("#{@context}_#{name}".to_sym)
        42:                true
        43:              else
        44:                super(name, include_private)
        45:              end
       
       System Info:
       ------------
       chef_version=13.2.20
       platform=debian
       platform_version=8.6
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
       program_name=chef-client worker: ppid=1120;start=22:14:08;
       executable=/opt/chef/bin/chef-client
```

Note that my metadata.rb in nomad_wrapper cookbook has the following:

`depends 'nomad', '= 0.12.1'`

And my recipes/default.rb in nomad_wrapper is including the nomad::default recipe:

`include_recipe 'nomad::default'`

Am I missing a step?  Googling didn't turn up many results for the above error, so I thought I'd post here and ask.

**Comment by nathwill** [comment]
this is almost certainly tied to the rollout of the new systemd 3.0 cookbook.  for now, if you pin to systemd 2.x, you should be able to use this as-is. 

long-term, i'm going to be doubling back and fixing this cookbook to use the upstreamed systemd_unit resource and removing the dependency on the systemd cookbook.

**Comment by wsoula** [comment]
@nathwill would you like a pr to at least fix default to run successfully?  https://github.com/nathwill/chef-nomad/compare/master...wsoula:support-latest-systemd?expand=1 . I tested with test kitchen on 14.04 where I was able to reproduce the error, running all the OSes failed due to some port conflict on my machine.

**Comment by nathwill** [comment]
@wsoula PRs welcome 👍 . happy to ship a release that supports v3 in the interim

**Comment by kmott** [comment]
I tried the workaround (pin systemd to 2.1.3) @nathwill and it seems to work okay now.  Thanks!

**Comment by wsoula** [comment]
@nathwill can you make that release please?  Thank you.
